name: BlockFox
version: '${project.version}'
main: de.lunarakai.blockfox.BlockFoxPlugin
api-version: '1.21'
depend:
  - CubesideUtils
  - LunarUtils
commands:
  blockfox:
    description: main command